#requirespackage 'PETSC_HAVE_GELUS'
ALL: lib

CFLAGS    =
FFLAGS    =
SOURCECU  = gelus.cu
SOURCEF   =
SOURCEH   = 
LIBBASE   = libpetscmat
DIRS      =
MANSEC    = Mat
LOCDIR    = src/mat/impls/aij/seq/gelus/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
