#requirespackage 'PETSC_HAVE_GELUS'

ALL: lib

CFLAGS   =
FFLAGS   =
SOURCECU = sorgelus.cu
SOURCEF  =
SOURCEH  =
LIBBASE  = libpetscksp
DIRS     =
MANSEC   = PC
LOCDIR   = src/ksp/pc/impls/sor/gelus/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test

